# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e21d2f7141de1aa86992b91ebea1950963d46236f8fadb7ad3c1563ebf1ce685572a11851c876f2669023ed7c6fb1bbc0f60448703fcc67e78045a0a2aa1c0ef

test:
  secret_key_base: 3b16b91e55b4cb6ed6610f208ea9a1c9f04731e561e17e5f0e17e5593f9a113d9b566e34a3b9e1c2fb3a670d1e4a8ba42ba4facaa592f79a3bc51a463cdb5453

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
